#!/usr/bin/perl
use v5.34.1;
use warnings;
use experimental qw[ try ];

use constant EXT_ALL_CLEAR => 0;
use constant EXT_USAGE_ERR => 64;
use constant EXT_NOT_FOUND => 66;

use lib './lib';
use Data::Dump           qw[ dd ];
use List::Util           qw[ first uniq min ];
use Time::HiRes          qw[ sleep ];
use RegexFactory         qw[ :all ];
use RegexFactory::Colors qw[ :all ];

our $VERSION = 'v0.0.1';

INIT {
    return if @ARGV == 2;

    print bld 'Usage:';
    print " regex-factory <file> <regex>\n";
    exit EXT_USAGE_ERR
}

my $file;
INIT {
    $file = shift;

    try {
        die ['{File not found}', EXT_NOT_FOUND]
            unless -e $file;
        
        die ['{File is not readable}', EXT_NOT_FOUND]
            unless -r $file;
        
        die ['{Path leads to a directory}', EXT_USAGE_ERR]
            unless -e $file;

    } catch ($e) {
        report_error $file, @$e
    }
}

my ($regex, $flags);
INIT {
    my $raw_input = shift;
    
    try {
        my $input  = $raw_input;
        
        my ($s_begin, $body, $escs_end, $s_end);
        ($s_begin, $input)       = $input =~ /^(\/|)(.+)/;
        ($input, $s_end, $flags) = $input =~ /(.+?)(?:(\/)([a-z]*)|)$/i;
        ($body, $escs_end)       = $input =~ /(.+?(\\*))$/;

        $flags //= '';
        if (defined $s_end and verify_odd_escapes $escs_end) {
            $body .= "/$flags";
            $flags = ''
            
        } elsif ($flags =~ /([^gimsx])/) {
            die "{Unknown regexp modifier \"/$&\"}"
        }

        $body =~ s/(\\*\/)/
            (verify_odd_escapes $1) ? "\\$1" : $1
        /eg;

        eval qq"'' =~ /$body/$flags; 1" or die $!;
        $regex = qr/$body/;

        # Todo:
        # - Write tests

        # Todo:
        # Improve regex metacharacters highlighting:
        # \w*, \w+, \w?     - \+ must have the same color of 'w'
        # *?, +?            - special colors when preceded by a group closing
        # \w*?, \w+?        - \+?* must have the same color of 'w'
        # \n, \t, \r, \f... - \ must have the same color of n, t, r...
        # [^...]            - must be distinct of [...], possibly in red
        # (?:...)           - no colors for '(?:' or ')'
        # (...)             - group must not interfere in the content coloring

        # Todo:
        # Improve group highlighting (phase 1):
        # ln 1: (...) - openning and closing must have an 'unique' color
        # ln 2: ^...^ - that 'unique' color must be also displayed bellow

        # Todo:
        # Improve group highlighting (phase 2):
        # ln 1:   (?<foo>...(...))...(?:...)...(...)...(?<bar>...)
        # ln 2:   ^1........^2..^^.............^3..^...^4........^
        # ...
        # ln x:   Group 1    Group 2    Group 3    Group 4
        # ln x+1: [.....]    [.....]    [.....]    [.....]

        # Todo:
        # Improve group highlighting (phase 3):
        # ln 1:   (?<foo>...(...))...(?:...)...(...)...(?<bar>...)
        # ln 2:   ^..foo....^1..^^.............^2..^...^..bar....^
        # ...
        # ln x:   Group foo    Group bar    Group 1    Group 2
        # ln x+1: [.......]    [.......]    [.....]    [.....]

        print ylw "'$raw_input'";
        print mgt ' :: ';
        print style_regex $body;

        print(
            ($flags)
            ? bld $flags
            : ' (no flags)'
        );

        print "\n";
            
    } catch ($e) {
        say $e;
        exit 0;
        report_error $raw_input, $e, EXT_USAGE_ERR
    }
}

open my $fh, '<', $file or die;

my @matches;
my @u_matches;

my $global = $flags =~ /g/;
my $line_number = 0;

while (my $line = <$fh>) {
    $line_number++;
    
    my ($m) = eval "\$line =~ /$regex/$flags";
    next unless $m;

    my $m_data =
        first { $$_[0] eq $m }
        @u_matches;
    
    push @u_matches, ($m_data = [ $m, 0 ]) unless $m_data;
    push @matches, [$m, $line_number];

    $$m_data[1]++;
    last unless $global;
}

close $fh;

@u_matches = sort { $$b[1] <=> $$a[1] } @u_matches;
my $n_matches = @matches;
my $u_matches = @u_matches;

if ($n_matches > 0 and !$global) {
    my $l = pop @{ $matches[0] };
    print bgr "Found match beginning at line $l"
    
} elsif ($n_matches > 0) {
    print match_counter mgt '# Total matches:', $n_matches;
    print matches_list { ":$_[1] $_[0]" } 10, @matches;
    print "\n";

    print match_counter red '# Unique matches:', $u_matches;
    print matches_list { "$_[0] ($_[1])" } 5, @u_matches
    
} else {
    print brd 'No matches found!'
}

print "\n" x 2;

1
